### ISSUE TITLE
[FEATURE REQUEST] Get a list of reminders and their status (done / not done)

### ISSUE THREAD

**Issue by Jinjinov** [jonahar/google-reminders-cli#1]
Would it be possible to get a list of reminders with their status?

Google Calendar API provides no way of knowing if the reminder has been marked as "done".

I am willing to help implement this feature, but I don't even know where to begin.

I have 18 years of experience programming desktop applications with C# but almost no experience programming for web.

**Comment by jonahar** [comment]
I also have almost no experience with web :)
Google doesn't provide a standard API for 'reminders', so it requires monitoring the requests and responses in the web calendar. I'll try to take a look at it. Will update.

**Comment by Jinjinov** [comment]
Thank you!

I don't even know how to monitor the requests and responses in the web calendar.

**Comment by jonahar** [comment]
I made some changes and created a client that supports more operations other than add, including listing reminders. However, these features are not yet visible to the user. The next step will probably be to integrate them into the main program so the user can benefit them. After that, we can move to inspect the reminder object and find whether a reminder is done or not.

**Comment by jonahar** [comment]
Done reminders are now printed with strikethrough.
You can modify the printing as you wish. A Reminder object has a field indicating whether it is done or not.

![strikethrough](https://i.imgur.com/JXFNpvn.png)

**Comment by Jinjinov** [comment]
Thank you so much!
As soon as I find some free time, I will try this out!
