### ISSUE TITLE
Port of your python code to js and php

### ISSUE THREAD

**Issue by Jinjinov** [jonahar/google-reminders-cli#6]
I apologize for contacting you here, I couldn't find your email address.

I tried to port your python code to JavaScript and PHP, but since I am C# desktop programmer with little web programming experience, I can't find the error in the ported code.

I managed to get the Google authentication working in JavaScript and PHP, but then I got stuck.

I have spent about 10 hours debugging the code, but I still get a HTTP Bad Request error code 400 in the JavaScript version and the HTTP Not Found error code 404 in the PHP version.

If you or anyone you know would be willing to take a look at the JavaScript and PHP ported code, I would be really grateful:

https://github.com/Jinjinov/google-reminders-js

https://github.com/Jinjinov/google-reminders-php

Thank you for writing the python code!

**Comment by jonahar** [comment]
I'm not very experienced with js or php. I'll leave this issue open for a while in case someone else could help with that.

**Comment by Jinjinov** [comment]
Thank you! Could you perhaps tag this issue with the "help wanted" label?

**Comment by Jinjinov** [comment]
After 12 hours of intense debugging and help from stackoverlow I have managed to get both Js and Php versions working :)

I couldn't have done it without your Python code, thank you!

By the way, I have found out that hour, minute and second parameters are optional, so in my code inside the build_reminder function I check if '4' exists in r['5'] before accessing r['5']['4']
